# Generated by Django 5.0.6 on 2024-11-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_product_is_frozen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_biodegradable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
