# Generated by Django 5.1.3 on 2024-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_product_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fathers_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mothers_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
