# Generated by Django 5.0.6 on 2024-11-24 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_fathers_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (11 digits starting with 013-019).', regex='^(013|014|015|016|017|018|019)\\d{8}$')]),
        ),
    ]
