# Generated by Django 5.0.6 on 2025-01-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_checkout'),
        ('management', '0020_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='age',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='management.cartitem'),
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
