# Generated by Django 5.0.6 on 2025-01-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_age_order_area_rename_name_order_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='area',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
